WebDeposito/WebDeposito/WebDeposito/Controllers/ArticuloController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using WebDeposito.Models;

namespace WebDeposito.Controllers
{
    public class ArticuloController : Controller
    {
        private HttpClient _client;
        private string _baseUrl;
        private static int actualPage;
        public ArticuloController()
        {
            _client = new HttpClient();
            _baseUrl = "http://localhost:5091/api/Articulos/";
        }
        public IActionResult Index(DateTime startdate, DateTime enddate)
        {
            string token = HttpContext.Session.GetString("token");
            if (string.IsNullOrEmpty(token) || HttpContext.Session.GetString("rol") != "Encargado")
            {
                return RedirectToAction("Login", "Login", new { mensaje = "No Autorizado." });
            }
            _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
                "Bearer",
                token
            );
            if (actualPage < 1) { actualPage = 1; }
            HttpRequestMessage solicitud =
            new HttpRequestMessage(HttpMethod.Get, new Uri(_baseUrl + "GetByFechas/" + "Page/" + actualPage
            + "/startdate=" + startdate.ToString("yyyy-MM-dd") + "/enddate=" + enddate.ToString("yyyy-MM-dd")));
            Task<HttpResponseMessage> respuesta = _client.SendAsync(solicitud);
            respuesta.Wait();
            if (respuesta.Result.IsSuccessStatusCode)
            {
                if (respuesta.Result.StatusCode == System.Net.HttpStatusCode.NoContent)
                {
                    ViewBag.mensaje = "No hay resultados.";
                    actualPage = 1;
                    return View();
                }
                var objetoComoTexto = respuesta.Result.Content.ReadAsStringAsync().Result;
                var articulos = JsonConvert.DeserializeObject<IEnumerable<ArticuloModel>>(objetoComoTexto);
                return View(articulos);
            }
            
            return View();
        }
        
        public IActionResult GetFechas(string mensaje)
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("token")) && HttpContext.Session.GetString("rol") == "Encargado")
            {
                ViewBag.mensaje = mensaje;
                return View();
            }
            return RedirectToAction("Login", "Login", new { mensaje = "No autorizado" });
        }
        [HttpPost]
        public IActionResult GetFechas(DateTime start, DateTime end) 
        {
            if (!string.IsNullOrEmpty(HttpContext.Session.GetString("token")) && HttpContext.Session.GetString("rol") == "Encargado")
            {
                if (start > end || start == null || end == null) return RedirectToAction("Index", new { mensaje = "Fechas no validas." });
                return RedirectToAction("Index", new { startdate = start, enddate = end });
            }
            return RedirectToAction("Login", "Login", new { mensaje = "No autorizado" });
        }
        [HttpPost]
        public ActionResult Next()
        {

            try
            {
                string mensaje = "";
                actualPage++;
                if (actualPage < 1)
                {
                    actualPage = 1;
                    mensaje = "Solo números positivos.";
                }

                return RedirectToAction("Index", new { message = mensaje });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Movimiento", new { mensaje = "Hubo un error" });
            }

        }

        [HttpPost]
        public ActionResult Previous()
        {


            try
            {
                string message = "";
                actualPage--;
                if (actualPage < 1)
                {
                    actualPage = 1;
                    message = "Only postive numbers allowed";
                }

                return RedirectToAction("Index", new { message = message });
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Movimiento", new { mensaje = "Hubo un error" });
            }
        }
    }
}

WebDeposito/WebDeposito/WebDeposito/Controllers/ReporteController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net.Http.Headers;
using WebDeposito.Models;

namespace WebDeposito.Controllers
{
    public class ReporteController : Controller
    {
        private HttpClient _client;
        private string _baseUrl;
        public ReporteController()
        {
            _client = new HttpClient();
            _baseUrl = "http://localhost:5091/api/Movimientos/GetMovsXFecha";
        }
        // GET: ReporteController
        public ActionResult Index(string mensaje)
        {
            string token = HttpContext.Session.GetString("token");
            if (string.IsNullOrEmpty(token) || HttpContext.Session.GetString("rol") != "Encargado")
            {
                return RedirectToAction("Login", "Login", new { mensaje = "No Autorizado." });
            }
            _client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue(
                "Bearer",
                token
            );
            ViewBag.mensaje = mensaje;

                HttpRequestMessage solicitud =
                new HttpRequestMessage(HttpMethod.Get, new Uri(_baseUrl));
                Task<HttpResponseMessage> respuesta = _client.SendAsync(solicitud);
                respuesta.Wait();
                if (respuesta.Result.IsSuccessStatusCode)
                {
                    if (respuesta.Result.StatusCode == System.Net.HttpStatusCode.NoContent)
                    {
                        ViewBag.mensaje = "No hay resultados.";
                        return View();
                    }
                    var objetoComoTexto = respuesta.Result.Content.ReadAsStringAsync().Result;
                    var movs = JsonConvert.DeserializeObject<IEnumerable<FechaModel>>(objetoComoTexto);
                    return View(movs);
                }

                return View();
            }
    }
}

WebDeposito/WebDeposito/WebDeposito/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebDeposito</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebDeposito.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movimiento" asp-action="Index">WebDeposito</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movimiento" asp-action="Index">Movimientos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reporte" asp-action="Index">Reporte por Fecha</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Articulo" asp-action="GetFechas">Buscar Articulos Por Fecha</a>
                        </li>
                        @if (!string.IsNullOrEmpty(Context.Session.GetString("token")))
                        {
                            <li class="nav-item position-absolute top-0 end-0">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">
                                    <button type="button" class="btn btn-danger">Logout</button>
                                </a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>