ObligatorioMartinattoGonzalezM3C/Papeleria.Web/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Papeleria.LogicaAplicacion.DTOs;
using Papeleria.LogicaAplicacion.InterfacesCasosDeUso.Administrador;

namespace Papeleria.Web.Controllers
{
    public class AdminController : Controller
    {
        private ICrearAdmin _crearAdmin;
        private IEditarAdmin _editarAdmin;
        private IEncontrarAdmins _encontrarAdmins;
        private IFindAdminById _findAdminById;
        private IBorrarAdmin _borrarAdmin;
        public AdminController(ICrearAdmin crearAdmin, IEditarAdmin editarAdmin, 
            IEncontrarAdmins encontrarAdmins, IFindAdminById findAdminById, IBorrarAdmin borrarAdmin)
        {
            this._encontrarAdmins = encontrarAdmins;
            this._crearAdmin = crearAdmin;
            this._editarAdmin = editarAdmin;
            this._findAdminById = findAdminById;
            this._borrarAdmin = borrarAdmin;
        }
        // GET: AdminController
        public ActionResult Index()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("usuario")))
            {
                return RedirectToAction("Index", "Login", new { mensaje = "Por favor inicie sesion" });
            }
            return View(_encontrarAdmins.FindAllAdmins());
        }

        // GET: AdminController/Create
        public ActionResult Create(string mensaje)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("usuario")))
            {
                return RedirectToAction("Index", "Login", new { mensaje = "Por favor inicie sesion" });
            }
            ViewBag.mensaje = mensaje;
            return View();
        }

        // POST: AdminController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UsuarioDTO adminDto)
        {
            try
            {
                this._crearAdmin.CrearAdmin(adminDto);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                return RedirectToAction("Create", new {mensaje = ex.Message});
            }
        }

        // GET: AdminController/Edit/5
        public ActionResult Edit(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("usuario")))
            {
                return RedirectToAction("Index", "Login", new { mensaje = "Por favor inicie sesion" });
            }
            UsuarioDTO admin = this._findAdminById.FindAdminById(id);
            return View(admin);
        }

        // POST: AdminController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UsuarioDTO adminDto)
        {
            this._editarAdmin.EditarAdmin(adminDto);
            return View(adminDto);
        }

        // GET: AdminController/Delete/5
        public ActionResult Delete(int id)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("usuario")))
            {
                return RedirectToAction("Index", "Login", new { mensaje = "Por favor inicie sesion" });
            }
            UsuarioDTO admin = this._findAdminById.FindAdminById(id);
            return View(admin);
        }

        // POST: AdminController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(UsuarioDTO admin, int id)
        {
            this._borrarAdmin.BorrarAdmin(id);
            return RedirectToAction("Index");
        }
    }
}

ObligatorioMartinattoGonzalezM3C/Papeleria.Web/Controllers/ArticulosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Papeleria.LogicaAplicacion.DTOs;
using Papeleria.LogicaAplicacion.InterfacesCasosDeUso.Articulo;

namespace Papeleria.Web.Controllers
{
    public class ArticulosController : Controller
    {

        private IEncontrarArticulos _encontrarArticulos;
        private ICrearArticulo _crearArticulo;
        public ArticulosController(IEncontrarArticulos encontrarArticulos, ICrearArticulo crearArticulo)
        {
            _encontrarArticulos = encontrarArticulos;
            _crearArticulo = crearArticulo;
        }

        // GET: ArticulosController
        public ActionResult Index()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("usuario")))
            {
                return RedirectToAction("Index", "Login", new { mensaje = "Por favor inicie sesion" });
            }
            return View(this._encontrarArticulos.EncontrarArticulos());
        }

        // GET: ArticulosController/Create
        public ActionResult Create()
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("usuario")))
            {
                return RedirectToAction("Index", "Login", new { mensaje = "Por favor inicie sesion" });
            }
            return View();
        }

        // POST: ArticulosController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ArticuloDTO articulo)
        {
            try
            {
                this._crearArticulo.CrearArticulo(articulo);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

ObligatorioMartinattoGonzalezM3C/Papeleria.Web/Controllers/ClientesController.cs
using Microsoft.AspNetCore.Mvc;
using Papeleria.LogicaAplicacion.DTOs;
using Papeleria.LogicaAplicacion.InterfacesCasosDeUso.Cliente;

namespace Papeleria.Web.Controllers
{
    public class ClientesController : Controller
    {

        private IEncontrarClientes _encontrarClientes;
        private IGetClientesXnombreYapellido _xnombreYapellido;
        private IGetClientesXmonto _xMonto;

        public ClientesController(IEncontrarClientes encontrarClientes, IGetClientesXnombreYapellido xnombreYapellido, IGetClientesXmonto xMonto)
        {
            _encontrarClientes = encontrarClientes;
            _xnombreYapellido = xnombreYapellido;
            _xMonto = xMonto;
        }



        // GET: ClientesController
        public ActionResult Index(string mensaje, string filtro)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("usuario")))
            {
                return RedirectToAction("Index", "Login", new { mensaje = "Por favor inicie sesion" });
            }
            IEnumerable<ClienteDTO> toShow = new List<ClienteDTO>();
            ViewBag.Mensaje = mensaje;
            ViewBag.Clientes = this._encontrarClientes.FindAllClientes();

            if (string.IsNullOrEmpty(filtro))
            {
                toShow = _encontrarClientes.FindAllClientes();
            }
            if (filtro == "PorNombre")
            {
                string nombreCliente = (string)TempData["NombreCliente"];
                toShow = this._xnombreYapellido.GetClientesXnombreYapellido(nombreCliente);
            }
            if(filtro == "PorMonto")
            {
                double monto;
                if(double.TryParse(TempData["Monto"].ToString(), out monto)) toShow = this._xMonto.GetClientesXmonto(monto);
            }
            return View(toShow);
        }

        [HttpPost]
        public ActionResult FiltrarPorNombre (string nombreCliente)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("usuario")))
            {
                return RedirectToAction("Index", "Login", new { mensaje = "Por favor inicie sesion" });
            }
            if (nombreCliente == null)
            {
                return RedirectToAction("Index");
            }
            TempData["NombreCliente"] = nombreCliente;
            return RedirectToAction("Index", new { filtro = "PorNombre" });
        }

        [HttpPost]
        public ActionResult FiltrarPorMonto (double monto)
        {
            if (string.IsNullOrEmpty(HttpContext.Session.GetString("usuario")))
            {
                return RedirectToAction("Index", "Login", new { mensaje = "Por favor inicie sesion" });
            }
            if (monto <= 0)
            {
                return RedirectToAction("Index", new { mensaje = "Monto invalido." });
            }
            TempData["Monto"] = monto.ToString();
            return RedirectToAction("Index", new { filtro = "PorMonto" });
        }

    }
}

ObligatorioMartinattoGonzalezM3C/Papeleria.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Papeleria.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Papeleria.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Papeleria del Tuki</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (!string.IsNullOrEmpty(Context.Session.GetString("usuario")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        }
                        @if (string.IsNullOrEmpty(Context.Session.GetString("usuario")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                            </li>
                        }
                        @if (!string.IsNullOrEmpty(Context.Session.GetString("usuario")))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Listar Admins</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Listar Clientes</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Articulos" asp-action="Index">Listar Articulos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pedidos" asp-action="Index">Listar Pedidos</a>
                            </li>
                            <li class="nav-item position-absolute top-0 end-0"><a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout"><button type="button" class="btn btn-danger">Logout</button>
                            
                            </a>

                            </li>
                        } 
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Papeleria.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.2/jquery.validate.min.js"
            integrity="sha512-TDj9O4u+PZjjwb8ncPJB3+9T9MWDcc5g9jD7P1d+uEdrA9zXpSH1R6qxCu2PBPJmHf7OZIayYi0pA8Cf5+/k7w=="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js"
            integrity="sha512-jx0lNneI0P2Pdv9n/V8ocwogDEiLbIKx3l/dsA+cj9bb15VfhpxXhTLRdF5bP71WlX6Z3s2U4W6Xx1zEdj0bnA=="
            crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>